/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini.proyecto;

import clases.Curso;
import clases.DetalleFactura;
import clases.EncabezadoFactura;
import clases.Estudiante;
import clases.Profesor;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC01
 */
public class GenerarFactura extends javax.swing.JFrame {
    DefaultTableModel dtmFactura = new DefaultTableModel();
    ObjectContainer BaseD = Db4o.openFile(MiniProyecto.direccionBD);

    /**
     * Creates new form EncabezadoFacturaInt
     */
    public GenerarFactura() {
        initComponents();
        setModelo();
        setLista();
        
        
    }
    
    private void setModelo() {
       String[] cabeceraTable = {"NOMBRE CURSO", "PROFESOR", "UNITARIO","CANTIDAD", "VALOR"};
       dtmFactura.setColumnIdentifiers(cabeceraTable);       
       jTable1.setModel(dtmFactura);
       
       // BaseD.set(new Curso("123", "Base de datos", "10:00:34", 34.0, "BD desde cero", "Aprenderemos los fundamentos de la base de datos" , "123", "123"));
       // BaseD.set(new Curso("1234", "POO", "10:00:34", 34.0, "Metodologia de programacion", "Aprenderemos los fundamentos de la base de datos" , "123", "123"));
       // BaseD.set(new Profesor("234", "345", "Informatica", new Date(), 345.6, "123", "Sebastian", "Avila", "Ecuador", "sebas@gmail.com", "1234567890"));
       // BaseD.set(new Estudiante(new Date(), "Avanzado", "123", "Migue", "Zhunio", "Ecuador", "miguel@gmail.com", "123"));
    }
    

    
    public void setLista() { // Llenar lista
       Curso curso;
       ObjectSet GenerarReporteCurso =  BaseD.get(new Curso(null, null, null, 0, null, null, null, null));
       
        if (GenerarReporteCurso.isEmpty()) {
            
        } else {
            while(GenerarReporteCurso.hasNext()) {
                curso = (Curso) GenerarReporteCurso.next();
                String nombreCurso = curso.getNombre_cur();
                ListCurso.addItem(nombreCurso);
           
            }
        }
        
    }
    public void setTabla() {
//        Object[] datos = new Object[dtmFactura.getColumnCount()];
//         
//        for (int j = 0; dtmFactura.getRowCount() > j; j++) {
//            dtmFactura.removeRow(0);
//        }
//        int i = 0;
//        dtmFactura.setRowCount(0);
//        ArrayList<Curso> listadoCursos = new ArrayList<>();
//        Curso in;
//        ObjectSet consultaPais = AcademiaWeb.Base.get(new Pais(null, null, 0 ,0));
//        for (int j = 0; j < consultaPais.size(); j++) {
//            in = (Pais) consultaPais.get(j);
//            listadoPaises.add(in);
//            in = new Pais();
//        }
//        for (Curso pais: ) {
//             datos[0] = pais.getCodigo_pais();
//             datos[1] = pais.getNombre_pais();
//             datos[2] = pais.getNumero_hab();
//             datos[3] = pais.getNum_est();
//             dtmPersonas.addRow(datos);
//             i++;
//        }
//         jTable1.setModel(dtmPersonas);
    }
    
    public Double setSuma() {
        Double valorFila = 0.0;
        Double total = 0.0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            valorFila = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            total += valorFila;
            
        }
        
        return total;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnElegirCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtCedula = new javax.swing.JFormattedTextField();
        SpCant = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btnEleminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtIva = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Generar Factura");

        jLabel2.setText("ID Cliente");

        jLabel3.setText("Curso");

        btnElegirCurso.setText("Elegir");
        btnElegirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirCursoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("IVA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Subtotal");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Descuento");

        txtSubtotal.setBackground(new java.awt.Color(153, 153, 0));

        txtTotal.setBackground(new java.awt.Color(153, 153, 0));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });

        jLabel8.setText("Cant");

        btnEleminar.setText("Eliminar");
        btnEleminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jButton4.setText("Generar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ListCurso, 0, 140, Short.MAX_VALUE)
                            .addComponent(txtCedula))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpCant, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnElegirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEleminar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(btnCalcular)
                                .addGap(116, 116, 116)
                                .addComponent(jButton4)
                                .addGap(85, 85, 85))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegirCurso)
                    .addComponent(SpCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(btnEleminar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnCalcular)
                    .addComponent(jButton3))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Double Subtotal = setSuma();
        txtSubtotal.setText(Subtotal.toString());
        
        Double Iva = Double.parseDouble(txtIva.getText());
        
        Double Descuento = Double.parseDouble(txtDescuento.getText());
        
        Double totalFactura;
        totalFactura = (Double) (Subtotal - (Subtotal*Descuento)/100) + ((Subtotal * Iva)/100);
        System.out.println(totalFactura);
        txtTotal.setText(totalFactura.toString());
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        String validarIdCedula = txtCedula.getText();
        
        
        
    }//GEN-LAST:event_txtCedulaFocusLost

    private void btnEleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEleminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarFactura().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElegirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirCursoActionPerformed
        
        // ObjectContainer BaseD = Db4o.openFile(MiniProyecto.direccionBD);
        int cant = (int) SpCant.getValue();
        String nombreCurso = ListCurso.getSelectedItem().toString();
        
        ObjectSet BuscarCurso =  BaseD.get(new Curso(null, nombreCurso, null, 0, null, null, null, null));   
        Curso cursoEscogido = (Curso) BuscarCurso.next();
        
        ObjectSet BuscarProfesor =  BaseD.get(new Profesor(null, null, null, null, 0, cursoEscogido.getId_pro(), null, null, null, null, null));
        Profesor profesor = (Profesor) BuscarProfesor.next();
        
        Object[] datos = new Object[dtmFactura.getColumnCount()];
        
        datos[0] = cursoEscogido.getNombre_cur();
        datos[1] = profesor.getNombre_per();
        datos[2] = cursoEscogido.getPrecio();
        datos[3] = cant;
        datos[4] = cursoEscogido.getPrecio() * cant;
        
        dtmFactura.addRow(datos);
            
        jTable1.setModel(dtmFactura);
        
        
        
    }//GEN-LAST:event_btnElegirCursoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        ObjectContainer BaseD = Db4o.openFile(MiniProyecto.direccionBD);
        DetalleFactura nuevoDetalle;
        String auxCedula = txtCedula.getText();
        ObjectSet BuscarEstudiante = BaseD.get(new Estudiante(null, null, auxCedula, null, null, null, null, null));
         
        if (!(BuscarEstudiante.isEmpty())) {
            int ulFactura = 0;
            ObjectSet ultimaFactura = BaseD.get(new EncabezadoFactura(0, null, 0, 0.0, 0.0, 0.0, null));
            if (ultimaFactura.isEmpty()) {
                ulFactura = 0;
            } else {
                EncabezadoFactura ultima = (EncabezadoFactura) ultimaFactura.next();               
                ulFactura = ultima.getCod_fac();
            }
            
            int ulDetalle = 0;
            ObjectSet ultimoDetalle = BaseD.get(new DetalleFactura("", 0, 0.0, null, null));
            if (ultimaFactura.isEmpty()) {
                ulDetalle = 0;
            } else {
                DetalleFactura ultimo = (DetalleFactura) ultimoDetalle.next();
                ulDetalle = Integer.parseInt(ultimo.getCod_det());
            }
            
            ulFactura += 1;
            BaseD.set(new EncabezadoFactura(ulFactura, new Date(), Integer.parseInt(txtIva.getText()), Integer.parseInt(txtTotal.getText()), Double.parseDouble(txtDescuento.getText()), Double.parseDouble(txtSubtotal.getText()), txtCedula.getText()));
            
            // ObjectSet UltimoEstudiante = BaseD.get(new DetalleFactura(null, 0, 0.0, null, null));
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String nombreCurso = jTable1.getValueAt(i, 0).toString();
                ObjectSet BuscarCurso =  BaseD.get(new Curso(null, nombreCurso, null, 0, null, null, null, null));   
                Curso cursoEscogido = (Curso) BuscarCurso.next();
                nombreCurso = cursoEscogido.getCod_cur();
                int cant = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
                Double valortotal = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
                ++ulDetalle;
                BaseD.set(new DetalleFactura(String.valueOf(ulDetalle),cant, valortotal, String.valueOf(ulFactura), nombreCurso));
                JOptionPane.showMessageDialog(null, "GUARDADO EXITOSAMENTE");
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ESE ALUMNO");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListCurso;
    private javax.swing.JSpinner SpCant;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnElegirCurso;
    private javax.swing.JButton btnEleminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIva;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
